apiVersion: v1
kind: Pod
metadata: 
  name: podwithsecreteinenv
spec: 
  containers: 
  - name: podwithsecreteinenv
    image: busybox
    args: 
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 30000
    env:
      - name: SECRET_USERNAME
        valueFrom: 
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: mysecret
            key: password
