apiVersion: v1
kind: Pod
metadata: 
  name: podwithsecrete
spec: 
  containers: 
  - name: podwithsecrete
    image: busybox
    args: 
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 30000
    volumeMounts: 
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes: 
  - name: foo
    secret:  
      secretName: mysecret